### PR TITLE
Create Documentation on x86_toolchain.sh 

### PR DESCRIPTION
**Pull request by Mateo-Manzano**
General documentation on common git commands.

### CODE REVIEW

**Review by LubosKuzma — COMMENTED** [review]
I don't understand this.
You want to run this at the end of the script? 
This will not work inside the shell script.
Please, implement actual feature.
Thank you,
L.

**Comment by Mateo-Manzano** [comment]
Hello Professor Lubos, I was trying to solve the create documentation suggestion in the README file, so I chose to document the most common git commands and useful arguments to use with. Thank you!

**Comment by LubosKuzma** [comment]
Well, this is not going to work. First of all, you're not making changes in the README file but in the main script. You can't just add any "documentation" text into a shell code. 
Second, to create documentation, you will need to do **much more** than just copy and paste git command's help. The documentation would tell everyone how to use the **shell code**, how to install it, what all the options are.
I am closing this pull request (you will have to make new one once ready) and I am giving you until Friday at midnight (basically two days) to finish this, otherwise I will be closing the repository and the assignment.
L.

**Comment by Mateo-Manzano** [comment]
Understood, thank you for the extra time. Have a good day!

**Pull request closed without merging**
